Created decorator pattern for new game object - star
matasx8/DesignPatternPlatformer pull request #14
Opened 2022-11-02 18:10 UTC by SuveizdisT

2022-11-02 18:42 UTC, matasx8 requested changes

2022-11-02 18:42 UTC, matasx8 commented on GameLibrary/GameClasses/Decorator/StarConfigurator.cs
> +    internal class StarConfigurator
Kodel tuscia klase palikai?

2022-11-02 18:42 UTC, matasx8 commented on GameLibrary/GameClasses/Decorator/MovingStar.cs
> +                    new Size2(16, 15)), this._go, true, true);
Ar tikrai turi buti (16, 15) o ne (16,16)? Atrodo kaip klaida, bet jeigu toks sprite dydis tai viskas ok

2022-11-02 18:42 UTC, matasx8 commented on GameLibrary/GameClasses/Decorator/StarCommand.cs
> +        public bool UndoWhenReady(GameTime gt)
UndoWhenReady turetu buti metodas is IUndoable interface. Dabar jis niekados nebus iskviestas, nes StarCommand neturi IUndoable.

2022-11-02 18:42 UTC, matasx8 commented on GameLibrary/GameClasses/Decorator/StarCommand.cs
> +    public class StarCommand : GOCommand
Ar tikrai reikia StarCommand? Atrodo identiskai kaip BouncyPotionCommand, galbut naudok ji?

2022-11-02 18:42 UTC, matasx8 commented on GameLibrary/GameClasses/GameObject.cs
> +        public Component UpdateComponent(Component oldCom, Component newCom)
Manau sito nereikia. Yra GetComponent metodas, kuris grazina reikiama komponenta ir ji tada gali pakeisti

2022-11-02 18:42 UTC, matasx8 commented on UntitledPlatformerGameServer/GameServer.cs
> +            loader.SpawnStar(star, registry.AllGameObjects, collisionSystem, 16, 13);
kodel vienur 16, 13 o kitur 16,15 ?

2022-11-02 23:15 UTC, SuveizdisT commented on GameLibrary/GameClasses/Decorator/StarConfigurator.cs
> +    internal class StarConfigurator
ištryniau

2022-11-02 23:16 UTC, SuveizdisT commented on GameLibrary/GameClasses/Decorator/MovingStar.cs
> +                    new Size2(16, 15)), this._go, true, true);
toks dydis :D

2022-11-02 23:16 UTC, SuveizdisT commented on GameLibrary/GameClasses/Decorator/StarCommand.cs
> +        public bool UndoWhenReady(GameTime gt)
Klasė panaikinta

2022-11-02 23:16 UTC, SuveizdisT commented on GameLibrary/GameClasses/Decorator/StarCommand.cs
> +    public class StarCommand : GOCommand
Pakeičiau į tą klasę

2022-11-02 23:18 UTC, SuveizdisT commented on GameLibrary/GameClasses/GameObject.cs
> +        public Component UpdateComponent(Component oldCom, Component newCom)
Vis dėlto palikau. Man reikia, kad žodyne pasikeistų reikšmė.

2022-11-02 23:18 UTC, SuveizdisT commented on UntitledPlatformerGameServer/GameServer.cs
> +            loader.SpawnStar(star, registry.AllGameObjects, collisionSystem, 16, 13);
Vienur common kitur moving star

2022-11-03 05:54 UTC, matasx8 approved these changes
puiku

2022-11-03 05:54 UTC, merged